name: Daily Code Format Check

on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
  workflow_dispatch:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Code Formatting
        uses: butr/actions-code-format-setup@v1.7
        with:
          workspace: "src/Bannerlord.Diplomacy.sln"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'artifixer, Katarn2000x, zijistark, bennyz'
          reviewers: 'artifixer, Katarn2000x, zijistark, bennyz'
